config/routes.rb
Rails.application.routes.draw do
  get 'presentations/new'

  get 'presentations/create'

  get 'matches/show'

  get 'rounds/show'

  devise_for :users

  resources :decks, :only => [:new, :create, :show]
  resources :tournaments, :only => [:new, :create, :index, :show] do
    resource :bracket, :only => [:new, :create, :update]
    resources :rounds, :only => [:show]
    resources :matches, :only => [:show, :update, :edit] do
      resources :votes, :only => [:create]
      resources :presentations, :only => [:new, :create]
    end
  end

  root 'site#index'
end

app/views/layouts/shared/_alerts.html.erb
<% flash.each do |key, value| %>
  <div class="alert-row">
    <div class="col-lg-12">
      <div class="alert alert-<%= alert_class_for(key) %> alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
        <%= value %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/shared/_navigation.html.erb
<!-- Navigation -->
<nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <%= link_to "BattleDecks", root_path, :class => "navbar-brand" %>
  </div>
  <!-- /.navbar-header -->

  <%= render 'layouts/shared/navigation/utility' %>

  <div class="navbar-default sidebar" role="navigation">
    <div class="sidebar-nav navbar-collapse">
      <ul class="nav" id="side-menu">
        <%#= render 'layout/shared/navigation/search' %>
        <% if user_signed_in? %>
        <li>
          <%= link_to "Upload a Deck", new_deck_path %>
        </li>

        <li>
          <a href="#"><i class="fa fa-gavel" aria-hidden="true"></i> Tournaments<span class="fa arrow"></span></a>
          <ul class="nav nav-second-level">
            <li>
              <%= link_to "Upcoming", tournaments_path %>
            </li>
            <li>
              <%= link_to "Managing", tournaments_path(:scope => "managing") %>
            </li>
            <li>
              <%= link_to "Playing", tournaments_path(:scope => "playing") %>
            </li>
            <li>
              <%= link_to "New Tournament", new_tournament_path %>
            </li>
          </ul>
        </li>
        <% else %>
        <li>
          <%= link_to new_user_registration_path do %>
            <i class="fa fa-user fa-fw"></i> Join BattleDecks
          <% end %>
        </li>        
        <li>
          <%= link_to new_user_session_path do %>
            <i class="fa fa-sign-in fa-fw"></i> Login to BattleDecks
          <% end %>
        </li>        
        <% end %>
        <%#= render 'layout/shared/navigation/main' %>
      </ul>
    </div>
    <!-- /.sidebar-collapse -->
  </div>
  <!-- /.navbar-static-side -->
</nav>