config/routes.rb
Rails.application.routes.draw do
  get 'presentations/new'

  get 'presentations/create'

  get 'matches/show'

  get 'rounds/show'

  devise_for :users

  resources :decks, :only => [:new, :create, :show]
  resources :tournaments, :only => [:new, :create, :index, :show] do
    resource :bracket, :only => [:new, :create, :update]
    resources :rounds, :only => [:show]
    resources :matches, :only => [:show, :update, :edit] do
      resources :votes, :only => [:create]
      resources :presentations, :only => [:new, :create]
    end
  end

  root 'site#index'
end

app/controllers/presentations_controller.rb
class PresentationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_tournament_and_match

  def new
    begin
      authorize @match, :upload_presentation?
    rescue Pundit::NotAuthorizedError
      flash[:error] = "You are not authorized to upload a presentation for this match."
      redirect_to tournament_match_path(@tournament, @match)
    end
  end

  def create
    if @match.submit_presentation(current_user, presentation_params)
      redirect_to tournament_match_path(@tournament, @match)
    else
      render :new
    end
  end

  private
    def presentation_params
      params.require(:match).permit(:player_1_presentation_url, :player_2_presentation_url)
    end
end

app/helpers/presentations_helper.rb
module PresentationsHelper
  def render_presentation_for(match, player_number)    
    upload_presentation = match.send("#{player_number}?", current_user) && 
                          !match.presentation_uploaded?(player_number)

    render 'presentations/match_presentation', :upload_presentation => upload_presentation
  end
end

app/views/presentations/_match_presentation.html.erb
<% if upload_presentation %>
  <%= link_to new_tournament_match_presentation_path(@tournament, @match), :class => "btn btn-primary btn-lg btn-block" do %>
    <i class="fa fa-youtube"></i> Upload Your Video
  <% end %>        
<% else %>          
  <img src="http://placehold.it/590x360" alt="ALT NAME" class="img-responsive" />
<% end %>

app/views/presentations/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Upload a Your Presentation</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= form_for(@match, :url => tournament_match_presentations_path(@tournament, @match), :method => :post, :role => "form") do |f| %>
      <div class="form-group">
        <%= f.label :"#{@match.current_player(current_user)}_presentation_url", :class => "control-label" %>
        <%= f.text_field :"#{@match.current_player(current_user)}_presentation_url", :class => "form-control" %>
      </div>

      <%= f.submit "Upload Presentation", :class => "btn btn-default" %>
    <% end %>
  </div>
</div>