config/routes.rb
Rails.application.routes.draw do
  get 'presentations/new'

  get 'presentations/create'

  get 'matches/show'

  get 'rounds/show'

  devise_for :users

  resources :decks, :only => [:new, :create, :show]
  resources :tournaments, :only => [:new, :create, :index, :show] do
    resource :bracket, :only => [:new, :create, :update]
    resources :rounds, :only => [:show]
    resources :matches, :only => [:show, :update, :edit] do
      resources :votes, :only => [:create]
      resources :presentations, :only => [:new, :create]
    end
  end

  root 'site#index'
end

app/controllers/rounds_controller.rb
class RoundsController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @tournament = Tournament.find(params[:tournament_id])
  end
end

app/helpers/rounds_helper.rb
module RoundsHelper
end

app/views/rounds/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= @tournament.name %> - Round: <%= params[:id] %></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <section class="bracket">
      <% @tournament.rounds.each do |round_number, round_matches| %>
      <ul class="round round-<%= round_number %>">
        <% round_matches.each do |match| %>
        <li class="spacer">&nbsp;</li>

        <li class="game game-top <%= "winner" if match.winner_is?(match.player_1) %>"><%= match.player_1.email %></li>
        <li class="game game-spacer"><%= link_to "Watch", tournament_match_path(@tournament, match) %></li>
        <li class="game game-bottom <%= "winner" if match.winner_is?(match.player_2) %>"><%= match.player_2.email %></li>

        <li class="spacer">&nbsp;</li>
        <% end %>
      
        <% if @tournament.round_complete?(round_number) %>
          <li class="spacer">&nbsp;</li>
          <li><%= link_to "Generate Next Round", tournament_bracket_path(@tournament, :round => round_number+1), :method => :patch %></li>            
        <% end %>
      </ul>
      <% end %>
    </main>
  </div>
</div>