config/routes.rb
Rails.application.routes.draw do
  get 'presentations/new'

  get 'presentations/create'

  get 'matches/show'

  get 'rounds/show'

  devise_for :users

  resources :decks, :only => [:new, :create, :show]
  resources :tournaments, :only => [:new, :create, :index, :show] do
    resource :bracket, :only => [:new, :create, :update]
    resources :rounds, :only => [:show]
    resources :matches, :only => [:show, :update, :edit] do
      resources :votes, :only => [:create]
      resources :presentations, :only => [:new, :create]
    end
  end

  root 'site#index'
end

app/models/tournament.rb
# class PlayersValidator < ActiveModel::EachValidator
#   def validate(tournament, attribute, value)
#     # Validate the Quantity
#     if tournament.tournament_players.size < 3
#       tournament.errors[:players] << "Need at least 2 players in a tournament"
#     end
#   end
# end

class Tournament < ActiveRecord::Base
  attr_reader :player_ids_to_add

  belongs_to :commissioner, :class_name => "User"
  has_many :tournament_players
  has_many :players, :through => :tournament_players, :class_name => "User"

  validates :name, :presence => true
  # validates_with PlayerValidator
  # validate :players_validation

  has_many :matches

  def commissioner?(user)
    user == commissioner
  end

  def round_complete?(round)
    # if all the matches in the round have a winner
    # SELECT 1 FROM matches WHERE round = 1 AND winner IS NOT NILL
    matches.active.empty?
  end

  def has_rounds?
    matches.exists?
  end

  def winner_ids_for_round(round = 1)
    matches.round(round).collect{|m| m.winner_id}
  end

  def rounds
    # TODO: Try to get SQL grouping to work.
    matches.group_by{|m| m.round}
  end

  # TODO: Possibly Deprecate
  def has_round?(round = 1)
    matches.round(round).exists?
  end

  def self.upcoming
    all
  end

  def self.finished
    (1..5).to_a
  end

  def add_player(player)
    tournament_players.build(:player => player)
  end

  def available_players
    supperssion_ids = [commissioner.id] + self.player_ids
    User.where.not(:id => supperssion_ids.compact)
  end

  def player_ids_to_add=(player_ids)
    @player_ids_to_add = player_ids
    User.where(:id => player_ids).each{|player| add_player(player)}
    @player_ids_to_add
  end

  private
    def players_validation
      if self.tournament_players.size < 2
        self.errors[:player_ids_to_add] << "at least 2 players needed"
      end
    end
end

app/controllers/tournaments_controller.rb
class TournamentsController < ApplicationController
  before_action :authenticate_user!

  def index
    params[:scope] ||= "upcoming"

    @tournaments = if params[:scope] == "managing"
      current_user.managed_tournaments
    elsif params[:scope] == "playing"
      current_user.played_tournaments
    else
      Tournament.upcoming
    end
  end


  def new
    @tournament = current_user.managed_tournaments.build
  end

  def create
    @tournament = current_user.managed_tournaments.new(tournament_params)
    if @tournament.save
      redirect_to @tournament
    else
      flash.now[:error] = "Unable to create the tournament, error details below."
      render :new
    end
  end

  def show
    @tournament = Tournament.find(params[:id])
  end

  private

    def tournament_params
      params.require(:tournament).permit(:name, :player_ids_to_add => [])
    end

end

app/helpers/tournaments_helper.rb
module TournamentsHelper
end

app/views/tournaments/index.html.erb
<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header"><%= params[:scope].capitalize %> Tournaments</h1>
	</div>
</div>

<div class="row">
	<div class="col-lg-12">
		<div class="list-group">
			<% @tournaments.each do |tournament| %>
			<%= link_to tournament_path(tournament), :class => "list-group-item" do %>
				<div class="media">
					<span class="label label-info pull-right"><%= pluralize(tournament.players.size, "Player") %></span>
					<div class="pull-left">
					</div>
					<div class="media-body">
						<h4 class="media-heading"><%= tournament.name %></h4>
						<!-- <p>Página Ativa</p> -->
					</div>
				</div>
			<% end %>
			<% end %>
		</div>
	</div>
</div>

app/views/tournaments/new.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header">Make a New Tournament</h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <%= form_for(@tournament, :role => "form") do |f| %>
      <div class="form-group">
        <%= f.label :name, :class => "control-label" %>
        <%= f.text_field :name, :class => "form-control" %>
        <% if @tournament.errors[:name].any? %>
        <p class="help-block-error"><%= @tournament.errors.full_messages_for(:name).to_sentence %></p>
        <% end %>
      </div>

      <div class="form-group">
        <%= f.label :player_ids_to_add, "Choose Players", :class => "control-label" %>
        <%= f.collection_select :player_ids_to_add, @tournament.available_players, :id, :email, {}, {:class => "form-control", :multiple => true} %>
        <% if @tournament.errors[:player_ids_to_add].any? %>
        <p class="help-block-error"><%= @tournament.errors[:player_ids_to_add].to_sentence.capitalize %></p>
        <% end %>
      </div>

      <%= f.submit "Create Tournament", :class => "btn btn-default" %>
    <% end %>
  </div>
</div>

app/views/tournaments/show.html.erb
<div class="row">
  <div class="col-lg-12">
    <h1 class="page-header"><%= @tournament.name %></h1>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <div class="panel panel-default">
      <div class="panel-heading">
        Players
      </div>
      <!-- /.panel-heading -->
      <div class="panel-body">
        <div class="table-responsive">
          <table class="table table-striped">
            <thead>
              <tr>
                <th>#</th>
                <th>Email</th>
              </tr>
            </thead>
            <tbody>
              <% @tournament.players.each.with_index(1) do |player,i| %>
              <tr>
                <td><%= i %></td>
                <td><%= player.email %></td>
              </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-lg-12">
    <% if @tournament.has_rounds? %>
      <% @tournament.rounds.each do |round, matches| %>
        <%= link_to "Round #{round} - #{pluralize(matches.size, "Match")}", tournament_round_path(@tournament, round) %>
      <% end %>
    <% else %>
      <%= link_to new_tournament_bracket_path(@tournament), :class => "btn btn-primary btn-lg btn-block" do %>
        <i class="fa fa-list"></i> Generate a Bracket
      <% end %>
    <% end %>
  </div>
</div>